{
  "swagger": "2.0",
  "info": {
    "description": "<span id=\"section/Authentication/api_key\" data-section-id=\"section/Authentication/api_key\"></span>\n<span id=\"section/Authentication/user_token\" data-section-id=\"section/Authentication/user_token\"></span>\n<span id=\"section/Authentication/user_email\" data-section-id=\"section/Authentication/user_email\"></span>\n",
    "title": "Workday Strategic Sourcing Attachments API",
    "version": "1.0"
  },
  "host": "api.us.workdayspend.com",
  "basePath": "/services/attachments/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/attachments": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Filter attachments by multiple criteria.\n",
            "in": "query",
            "name": "filter",
            "type": "object"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "$ref": "#/definitions/Attachment"
                  },
                  "type": "array"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Returns a filtered list of attachments based of the `filter[id_equals]` mandatory param.\nThe result is limited to **50** attachments.\n",
        "operationId": "List Attachments",
        "summary": "List Attachments",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments\"\n"
          }
        ]
      },
      "post": {
        "consumes": [
          "application/vnd.api+json"
        ],
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentCreate"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentUpload"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Create an attachment for an object. This endpoint represents the first step in the two-step\nupload workflow, described in the [Working with Attachments](#section/Working-with-Attachments)\nsection.\n\nThe only required attribute is `file_name`, which will be used to generate attachment title\n(if a custom one is not supplied), and the upload URL. You will also need to specify the object\nto which you want to add an attachment (see `relationships` property).\n",
        "operationId": "Create an Attachment",
        "summary": "Create an Attachment",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     -X POST \\\n     -d '\n       {\n         \"data\": {\n           \"type\": \"attachments\",\n           \"attributes\": {\n             \"title\": \"My Interesting Document\",\n             \"file_name\": \"Some Interesting File.pdf\",\n             \"external_id\": \"AT1\"\n           },\n           \"relationships\": {\n             \"contract\": {\n               \"data\": {\n                 \"id\": 1,\n                 \"type\": \"contracts\"\n               }\n             }\n           }\n         }\n       }\n     ' \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments\"\n"
          }
        ]
      }
    },
    "/attachments/{external_id}/external_id": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Unique attachment external identifier.",
            "in": "path",
            "name": "external_id",
            "required": true,
            "type": "string",
            "x-example": "AT1"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/Attachment"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Retrieves the details of an existing attachment. You need to supply the unique attachment identifier (external ID) that was set during attachment creation.\n",
        "operationId": "Get an Attachment by External ID",
        "summary": "Get an Attachment by External ID",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments/AT1/external_id\"\n"
          }
        ]
      },
      "patch": {
        "consumes": [
          "application/vnd.api+json"
        ],
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Unique attachment external identifier.",
            "in": "path",
            "name": "external_id",
            "required": true,
            "type": "string",
            "x-example": "AT1"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentUpdate"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentUpload"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "$ref": "#/definitions/Errors"
            }
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Update an attachment for an object. This endpoint represents the first step in the two-step\nupdate upload workflow, described in the [Working with Attachments](#section/Working-with-Attachments)\nsection.\n\nNew `upload_url` and `upload_headers` will be returned when the `file_name` attribute is passed. In this case, the existing `upload_url` will be overridden with a new one that doesn’t have the associated file yet, pending completion of the second step in the described upload process.\n",
        "operationId": "Update an Attachment by External ID",
        "summary": "Update an Attachment by External ID",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     -X PATCH \\\n     -d '\n       {\n         \"data\": {\n           \"id\": \"AT1\",\n           \"type\": \"attachments\",\n           \"attributes\": {\n             \"title\": \"My Interesting Document\",\n             \"file_name\": \"Some Interesting File.pdf\"\n           }\n         }\n       }\n     ' \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments/AT1/external_id\"\n"
          }
        ]
      }
    },
    "/attachments/{id}": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Unique attachment identifier.",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer",
            "x-example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/Attachment"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Retrieves the details of an existing attachment. You need to supply the unique attachment identifier that was returned upon attachment creation.\n",
        "operationId": "Get an Attachment",
        "summary": "Get an Attachment",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments/1\"\n"
          }
        ]
      },
      "patch": {
        "consumes": [
          "application/vnd.api+json"
        ],
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Unique attachment identifier.",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer",
            "x-example": 1
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentUpdate"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AttachmentUpload"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "$ref": "#/definitions/Errors"
            }
          }
        },
        "tags": [
          "attachments"
        ],
        "description": "Update an attachment for an object. This endpoint represents the first step in the two-step\nupdate upload workflow, described in the [Working with Attachments](#section/Working-with-Attachments)\nsection.\n\nNew `upload_url` and `upload_headers` will be returned when the `file_name` attribute is passed. In this case, the existing `upload_url` will be overridden with a new one that doesn’t have the associated file yet, pending completion of the second step in the described upload process.\n",
        "operationId": "Update an Attachment",
        "summary": "Update an Attachment",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     -X PATCH \\\n     -d '\n       {\n         \"data\": {\n           \"id\": \"1\",\n           \"type\": \"attachments\",\n           \"attributes\": {\n             \"title\": \"My Interesting Document\",\n             \"file_name\": \"Some Interesting File.pdf\"\n           }\n         }\n       }\n     ' \\\n     \"https://api.us.workdayspend.com/services/attachments/v1/attachments/1\"\n"
          }
        ]
      }
    }
  },
  "definitions": {
    "Attachment": {
      "allOf": [
        {
          "$ref": "#/definitions/AttachmentBase"
        },
        {
          "properties": {
            "attributes": {
              "$ref": "#/definitions/AttachmentAttributes"
            }
          },
          "type": "object"
        }
      ]
    },
    "AttachmentAttributes": {
      "allOf": [
        {
          "$ref": "#/definitions/AttachmentAttributesExtended"
        },
        {
          "required": [
            "file_name"
          ],
          "type": "object"
        }
      ]
    },
    "AttachmentAttributesBase": {
      "description": "Attachment attributes.",
      "properties": {
        "external_id": {
          "description": "Attachment external identifier.",
          "example": "AT1",
          "maxLength": 255,
          "type": "string"
        },
        "file_name": {
          "description": "Attachment file name.",
          "example": "My Contract.pdf",
          "type": "string"
        },
        "file_size": {
          "description": "Attachment file size in bytes.",
          "example": "1023343",
          "readOnly": true,
          "type": "string"
        },
        "title": {
          "description": "Attachment title.",
          "example": "My Contract",
          "maxLength": 255,
          "type": "string"
        }
      },
      "type": "object"
    },
    "AttachmentAttributesExtended": {
      "allOf": [
        {
          "$ref": "#/definitions/AttachmentAttributesBase"
        },
        {
          "properties": {
            "download_url": {
              "description": "Attachment download URL.",
              "readOnly": true,
              "type": "string"
            },
            "download_url_expires_at": {
              "description": "Download URL expiration time.",
              "example": "2020-08-21T13:26:59.999Z",
              "format": "date-time",
              "readOnly": true
            },
            "uploaded_at": {
              "description": "Time of upload.",
              "example": "2020-08-18T12:48:42.978Z",
              "format": "date-time",
              "readOnly": true
            },
            "uploaded_by": {
              "description": "Email of the uploader.",
              "readOnly": true,
              "type": "string"
            }
          },
          "type": "object"
        }
      ]
    },
    "AttachmentBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/AttachmentId"
        },
        "type": {
          "$ref": "#/definitions/AttachmentType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Attachment",
      "type": "object"
    },
    "AttachmentContractRelationship": {
      "description": "Contract relationship.",
      "properties": {
        "contract": {
          "properties": {
            "data": {
              "$ref": "#/definitions/ContractBase"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "contract"
      ],
      "title": "Contract",
      "type": "object"
    },
    "AttachmentCreate": {
      "properties": {
        "attributes": {
          "allOf": [
            {
              "$ref": "#/definitions/AttachmentAttributesBase"
            },
            {
              "required": [
                "file_name"
              ],
              "type": "object"
            }
          ]
        },
        "relationships": {},
        "type": {
          "$ref": "#/definitions/AttachmentType"
        }
      },
      "required": [
        "type"
      ],
      "type": "object"
    },
    "AttachmentEventRelationship": {
      "description": "Event relationship.",
      "properties": {
        "event": {
          "properties": {
            "data": {
              "$ref": "#/definitions/EventBase"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "event"
      ],
      "title": "Event",
      "type": "object"
    },
    "AttachmentId": {
      "description": "Attachment identifier string.",
      "example": 1,
      "type": "integer"
    },
    "AttachmentInputFilter": {
      "properties": {
        "id_equals": {
          "description": "Find attachments by IDs. A comma separated list of IDs to be provided.",
          "example": "2,5,9",
          "type": "string"
        }
      },
      "type": "object"
    },
    "AttachmentProjectRelationship": {
      "description": "Project relationship.",
      "properties": {
        "project": {
          "properties": {
            "data": {
              "$ref": "#/definitions/ProjectBase"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "project"
      ],
      "title": "Project",
      "type": "object"
    },
    "AttachmentSupplierCompanyRelationship": {
      "description": "Supplier Company relationship.",
      "properties": {
        "supplier_company": {
          "properties": {
            "data": {
              "$ref": "#/definitions/SupplierCompanyBase"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "supplier_company"
      ],
      "title": "Supplier Company",
      "type": "object"
    },
    "AttachmentType": {
      "description": "Object type, should always be `attachments`.",
      "example": "attachments",
      "type": "string"
    },
    "AttachmentUpdate": {
      "properties": {
        "attributes": {
          "$ref": "#/definitions/AttachmentAttributesBase"
        },
        "id": {
          "$ref": "#/definitions/AttachmentId"
        },
        "type": {
          "$ref": "#/definitions/AttachmentType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "type": "object"
    },
    "AttachmentUpload": {
      "allOf": [
        {
          "$ref": "#/definitions/AttachmentBase"
        },
        {
          "properties": {
            "attributes": {
              "$ref": "#/definitions/AttachmentUploadAttributes"
            }
          },
          "type": "object"
        }
      ]
    },
    "AttachmentUploadAttributes": {
      "allOf": [
        {
          "$ref": "#/definitions/AttachmentAttributesBase"
        },
        {
          "properties": {
            "upload_headers": {
              "description": "List of required HTTP headers with their values to submit when uploading the attachment file.\n",
              "items": {
                "properties": {
                  "name": {
                    "description": "HTTP header name.",
                    "type": "string"
                  },
                  "value": {
                    "description": "HTTP header value.",
                    "type": "string"
                  }
                },
                "type": "object"
              },
              "readOnly": true,
              "type": "array"
            },
            "upload_url": {
              "description": "Attachment upload URL. Please note, the URL expires within 15 minutes. This attribute\nwill only be returned when creating a new attachment.\n",
              "readOnly": true,
              "type": "string"
            }
          },
          "required": [
            "file_name"
          ],
          "type": "object"
        }
      ]
    },
    "Contract": {
      "allOf": [
        {
          "$ref": "#/definitions/ContractBase"
        }
      ]
    },
    "ContractBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/ContractId"
        },
        "type": {
          "$ref": "#/definitions/ContractTypeValue"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Contract",
      "type": "object"
    },
    "ContractId": {
      "description": "Contract identifier string.",
      "example": 1,
      "type": "integer"
    },
    "ContractTypeValue": {
      "description": "Object type, should always be `contracts`.",
      "example": "contracts",
      "type": "string"
    },
    "Error": {
      "properties": {
        "detail": {
          "description": "A human-readable explanation specific to this occurrence of the problem.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Errors": {
      "properties": {
        "errors": {
          "items": {
            "$ref": "#/definitions/Error"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Event": {
      "allOf": [
        {
          "$ref": "#/definitions/EventBase"
        }
      ]
    },
    "EventBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/EventId"
        },
        "type": {
          "$ref": "#/definitions/EventType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Event",
      "type": "object"
    },
    "EventId": {
      "description": "Event identifier string.",
      "example": 1,
      "type": "integer"
    },
    "EventType": {
      "description": "Object type, should always be `events`.",
      "example": "events",
      "type": "string"
    },
    "Project": {
      "allOf": [
        {
          "$ref": "#/definitions/ProjectBase"
        }
      ]
    },
    "ProjectBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/ProjectId"
        },
        "type": {
          "$ref": "#/definitions/ProjectType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Project",
      "type": "object"
    },
    "ProjectId": {
      "description": "Project identifier string.",
      "example": 1,
      "type": "integer"
    },
    "ProjectType": {
      "description": "Object type, should always be `projects`.",
      "example": "projects",
      "type": "string"
    },
    "SupplierCompany": {
      "allOf": [
        {
          "$ref": "#/definitions/SupplierCompanyBase"
        }
      ]
    },
    "SupplierCompanyBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/SupplierCompanyId"
        },
        "type": {
          "$ref": "#/definitions/SupplierCompanyType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "SupplierCompany",
      "type": "object"
    },
    "SupplierCompanyId": {
      "description": "Supplier company identifier string.",
      "example": 1,
      "type": "integer"
    },
    "SupplierCompanyType": {
      "description": "Object type, should always be `supplier_companies`.",
      "example": "supplier_companies",
      "type": "string"
    }
  },
  "securityDefinitions": {
    "api_key": {
      "description": "Company API key.",
      "in": "header",
      "name": "X-Api-Key",
      "type": "apiKey"
    },
    "user_email": {
      "description": "User email.",
      "in": "header",
      "name": "X-User-Email",
      "type": "apiKey"
    },
    "user_token": {
      "description": "User token.",
      "in": "header",
      "name": "X-User-Token",
      "type": "apiKey"
    }
  },
  "security": [
    {
      "api_key": []
    }
  ],
  "tags": [
    {
      "description": "Workday Strategic Sourcing API Support: Please have a Named Support Contact from your company submit a support case in Workday's Customer Center.\n",
      "name": "support",
      "x-displayName": "Customer Support"
    },
    {
      "description": "### US Region\n| Environment       | US region Base URI                                              |\n|-------------------|-----------------------------------------------------------------|\n| **Production**    | https://api.us.workdayspend.com/services/attachments/v1         |\n| **Sandbox**       | https://api.sandbox.us.workdayspend.com/services/attachments/v1 |\n\n### EU Region\n| Environment       | EU region Base URI                                                |\n|-------------------|-------------------------------------------------------------------|\n| **Production**    | https://api.eu.workdayspend.com/services/attachments/v1          |\n| **Sandbox**       | https://api.sandbox.eu.workdayspend.com/services/attachments/v1  |\n\n### CA Region\n| Environment       | CA region Base URI                                                |\n|-------------------|-------------------------------------------------------------------|\n| **Production**    | https://api.ca.workdayspend.com/services/attachments/v1          |\n| **Sandbox**       | https://api.sandbox.ca.workdayspend.com/services/attachments/v1  |\n",
      "name": "servers",
      "x-displayName": "Servers"
    },
    {
      "description": "The API conforms to the [JSON API Specification](https://jsonapi.org).\n\nThe current version of this service is indicated by the `X-Api-Version` header.\n\nSample version header: `X-Api-Version: 1.0`.\n",
      "name": "api_specification",
      "x-displayName": "API Specification"
    },
    {
      "description": "The Workday Strategic Sourcing API uses API keys to authenticate requests. Every request\nwill require all 3 HTTP headers:\n\n| HTTP Header       | Description               |\n|-------------------|---------------------------|\n| **X-Api-Key**     | a company-wide API key    |\n| **X-User-Token**  | a user-specific API token |\n| **X-User-Email**  | user email                |\n\nYou can generate all of those from the _API tokens_ section of your _Profile_ page.\n\nYour API keys carry many privileges, so be sure to keep them secure! Do not share your secret API\nkeys in publicly accessible areas such as GitHub, client-side code, and so forth.\n\nAll API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made\nover plain HTTP will fail. API requests without authentication will also fail.\n",
      "name": "authentication",
      "x-displayName": "Authentication"
    },
    {
      "description": "Rate limit windows are per second and are shared by all API Keys for a company.\n\nThe rate limit is 5 requests per second.\n\nWhen request submissions exceed the limits, the limit-exceeding requests return `429 Too Many Requests` error responses to the client.\n\nUpon receiving a `429` response, it is recommended to retry the request in compliance with the rate limit. One example would be to add a sleep function for 1 second and retry.\n",
      "name": "rate_limiting",
      "x-displayName": "Rate Limiting"
    },
    {
      "description": "Use the attachments API to create, update, and delete the attachments in Workday Strategic Sourcing.\n\n## Working with Attachments\n\nCreating attachments for Workday Strategic Sourcing objects is a two-step process. First, you need to inform\nthe system about your intention to upload an attachment by issuing a \"Create an Attachment\" request,\nconsisting of the file name and a link to the object to which you are adding an attachment. The link\nis represented by a relationship object containing an object ID and its type.\n\nIn the response you will receive a link in the `upload_url` attributes, along with required HTTP headers\nto send with your file. You will need to upload your file as a binary stream in a PUT request into the\nspecified URL, making sure the required headers are present. Here is how the workflow might look\nlike when triggered from a console:\n\n```bash\n$ curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n       -H \"X-User-Token: ${USER_TOKEN}\" \\\n       -H \"X-User-Email: ${USER_EMAIL}\" \\\n       -H \"Content-Type: application/vnd.api+json\" \\\n       -X POST \\\n       -d '\n         {\n           \"data\": {\n             \"type\": \"attachments\",\n             \"attributes\": {\n               \"title\": \"My Interesting Document\",\n               \"file_name\": \"Some Interesting File.pdf\"\n             },\n             \"relationships\": {\n               \"contract\": {\n                 \"data\": {\n                   \"id\": 1,\n                   \"type\": \"contracts\"\n                 }\n               }\n             }\n           }\n         }\n       ' \\\n       \"https://api.us.workdayspend.com/services/attachments/v1/attachments\"\n\n{\n    \"data\": {\n        \"id\": \"1\",\n        \"type\": \"attachments\",\n        \"attributes\": {\n            \"title\": \"My Interesting Document\",\n            \"file_size\": null,\n            \"upload_url\": \"https://upload.s3.amazonaws.com/uploads/contract/1/hex/file.pdf?some=very&long=url\",\n            \"upload_headers\": [\n                {\n                    \"name\": \"Content-Type\",\n                    \"value\": \"application/octet-stream\"\n                },\n                {\n                    \"name\": \"x-amz-acl\",\n                    \"value\": \"private\"\n                },\n                {\n                    \"name\": \"x-amz-server-side-encryption\",\n                    \"value\": \"AES256\"\n                },\n                {\n                    \"name\": \"Content-Disposition\",\n                    \"value\": \"attachment\"\n                }\n            ]\n        }\n    }\n}\n\n$ curl -X PUT \\\n    --data \"@file.pdf\" \\\n    -H \"Content-Type: application/octet-stream\" \\\n    -H \"x-amz-acl: private\" \\\n    -H \"x-amz-server-side-encryption: AES256\" \\\n    -H \"Content-Disposition: attachment\" \\\n    https://upload.s3.amazonaws.com/uploads/contract/1/hex/file.pdf?some=very&long=url\n```\n\nThe upload URL expires within 15 minutes after issuing. Please note that you will not be able to upload\nthe data file to the attachment object after that. An automated system will purge all partial uploads\nafter a certain period (usually within 30-60 minutes after creation) to prevent orphan records from\noverflowing the system.\n\n**Please Note**: The list of headers and their values might change at any time, so when you're\nimplementing an integration with the Workday Strategic Sourcing system, make sure to include all of the HTTP headers\nreturned from the attachments endpoint.\n\n## Attachment Object\n\n<SchemaDefinition schemaRef=\"#/components/schemas/Attachment\" showReadOnly={true} showWriteOnly={true} />\n",
      "name": "attachments",
      "x-displayName": "Attachments"
    }
  ],
  "x-components": {
    "examples": {
      "create_request": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT1",
              "file_name": "Some Test File.pdf",
              "title": "My Test Document"
            },
            "relationships": {
              "contract": {
                "data": {
                  "id": 1,
                  "type": "contracts"
                }
              }
            },
            "type": "attachments"
          }
        }
      },
      "create_response": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT1",
              "file_size": null,
              "title": "My Test Document",
              "upload_headers": [
                {
                  "name": "Content-Type",
                  "value": "application/octet-stream"
                },
                {
                  "name": "x-amz-acl",
                  "value": "private"
                },
                {
                  "name": "x-amz-server-side-encryption",
                  "value": "AES256"
                },
                {
                  "name": "Content-Disposition",
                  "value": "attachment"
                }
              ],
              "upload_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Test%20File.pdf?some=very&long=url"
            },
            "id": "1",
            "type": "attachments"
          }
        }
      },
      "external_show_response": {
        "value": {
          "data": {
            "attributes": {
              "download_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Updated%20Test%20File.pdf?some=very&long=url",
              "download_url_expires_at": "2020-08-21T13:26:59.999Z",
              "external_id": "AT1",
              "file_size": "1023343",
              "title": "My Test Document",
              "uploaded_at": "2020-08-18T12:48:42.978Z",
              "uploaded_by": "someone@example.com"
            },
            "id": "1",
            "links": {
              "self": " https://api.us.workdayspend.com/services/attachments/v1/attachments/1"
            },
            "type": "attachments"
          }
        }
      },
      "external_update_request": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT2",
              "file_name": "Some Updated Test File.pdf",
              "title": "My Updated Test Document"
            },
            "id": "AT1",
            "type": "attachments"
          }
        }
      },
      "external_update_response": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT2",
              "file_size": null,
              "title": "My Updated Test Document",
              "upload_headers": [
                {
                  "name": "Content-Type",
                  "value": "application/octet-stream"
                },
                {
                  "name": "x-amz-acl",
                  "value": "private"
                },
                {
                  "name": "x-amz-server-side-encryption",
                  "value": "AES256"
                },
                {
                  "name": "Content-Disposition",
                  "value": "attachment"
                }
              ],
              "upload_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Updated%20Test%20File.pdf?some=very&long=url"
            },
            "id": "1",
            "type": "attachments"
          }
        }
      },
      "index_response": {
        "value": {
          "data": [
            {
              "attributes": {
                "download_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Updated%20Test%20File.pdf?some=very&long=url",
                "download_url_expires_at": "2020-08-18T13:26:59.999Z",
                "external_id": "AT1",
                "file_size": "1023343",
                "title": "My Test Document",
                "uploaded_at": "2020-08-18T12:48:42.978Z",
                "uploaded_by": "someone@example.com"
              },
              "id": "1",
              "links": {
                "self": " https://api.us.workdayspend.com/services/attachments/v1/attachments/1"
              },
              "type": "attachments"
            },
            {
              "attributes": {
                "download_url": "https://upload.s3.amazonaws.com/uploads/contract/2/hex/Some%20Updated%20Test%20File2.pdf?some=very&long=url",
                "download_url_expires_at": "2020-08-19T13:26:59.999Z",
                "external_id": null,
                "file_size": "534241",
                "title": "My Test Document 2",
                "uploaded_at": "2020-08-19T12:48:42.978Z",
                "uploaded_by": "someone@example.com"
              },
              "id": "2",
              "links": {
                "self": " https://api.us.workdayspend.com/services/attachments/v1/attachments/2"
              },
              "type": "attachments"
            }
          ],
          "links": {
            "self": "https://api.us.workdayspend.com/services/attachments/v1/attachments"
          },
          "meta": {
            "count": 2
          }
        }
      },
      "show_response": {
        "value": {
          "data": {
            "attributes": {
              "download_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Updated%20Test%20File.pdf?some=very&long=url",
              "download_url_expires_at": "2020-08-21T13:26:59.999Z",
              "external_id": "AT1",
              "file_size": "1023343",
              "title": "My Test Document",
              "uploaded_at": "2020-08-18T12:48:42.978Z",
              "uploaded_by": "someone@example.com"
            },
            "id": "1",
            "links": {
              "self": " https://api.us.workdayspend.com/services/attachments/v1/attachments/1"
            },
            "type": "attachments"
          }
        }
      },
      "update_request": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT2",
              "file_name": "Some Updated Test File.pdf",
              "title": "My Updated Test Document"
            },
            "id": "1",
            "type": "attachments"
          }
        }
      },
      "update_response": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AT2",
              "file_size": null,
              "title": "My Updated Test Document",
              "upload_headers": [
                {
                  "name": "Content-Type",
                  "value": "application/octet-stream"
                },
                {
                  "name": "x-amz-acl",
                  "value": "private"
                },
                {
                  "name": "x-amz-server-side-encryption",
                  "value": "AES256"
                },
                {
                  "name": "Content-Disposition",
                  "value": "attachment"
                }
              ],
              "upload_url": "https://upload.s3.amazonaws.com/uploads/contract/1/hex/Some%20Updated%20Test%20File.pdf?some=very&long=url"
            },
            "id": "1",
            "type": "attachments"
          }
        }
      }
    }
  },
  "x-tagGroups": [
    {
      "tags": [
        "support",
        "servers",
        "api_specification",
        "authentication",
        "rate_limiting"
      ],
      "name": "Getting Started"
    },
    {
      "tags": [
        "attachments"
      ],
      "name": "Attachments"
    }
  ]
}