{
  "swagger": "2.0",
  "info": {
    "description": "<span id=\"section/Authentication/api_key\" data-section-id=\"section/Authentication/api_key\"></span>\n<span id=\"section/Authentication/user_token\" data-section-id=\"section/Authentication/user_token\"></span>\n<span id=\"section/Authentication/user_email\" data-section-id=\"section/Authentication/user_email\"></span>\n",
    "title": "Workday Strategic Sourcing Awards API",
    "version": "1.0"
  },
  "host": "api.us.workdayspend.com",
  "basePath": "/services/awards/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/award_line_items/{id}": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Unique Award Line Items identifier.",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "x-example": 15
          },
          {
            "description": "Use the `include` parameter to request related resources along with the primary resource.\n",
            "enum": [
              "supplier_company",
              "worksheet"
            ],
            "in": "query",
            "name": "include",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "$ref": "#/definitions/AwardLineItem"
                }
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "tags": [
          "award_line_items"
        ],
        "description": "Retrieves the details of an existing award line items. You need to supply the unique award line items\nidentifier.\n",
        "operationId": "Get an Award Line Item",
        "summary": "Get an Award Line Item",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/awards/v1/award_line_items/1_5\"\n"
          }
        ]
      }
    },
    "/awards": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Filter awards by multiple criteria.\n",
            "in": "query",
            "name": "filter",
            "type": "object"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "allOf": [
                {
                  "properties": {
                    "data": {
                      "items": {
                        "$ref": "#/definitions/Award"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                },
                {
                  "$ref": "#/definitions/Pagination"
                }
              ],
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "tags": [
          "awards"
        ],
        "description": "Returns a list of awards.",
        "operationId": "List Awards",
        "summary": "List Awards",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/awards/v1/awards\"\n"
          }
        ]
      }
    },
    "/awards/{award_id}/award_line_items": {
      "get": {
        "produces": [
          "application/vnd.api+json"
        ],
        "parameters": [
          {
            "description": "Award identifier.",
            "in": "path",
            "name": "award_id",
            "required": true,
            "type": "integer",
            "x-example": 1
          },
          {
            "description": "Filter awards line items by multiple criteria.\n",
            "in": "query",
            "name": "filter",
            "type": "object"
          },
          {
            "description": "Use the `include` parameter to request related resources along with the primary resource.\n",
            "enum": [
              "supplier_company",
              "worksheet"
            ],
            "in": "query",
            "name": "include",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "allOf": [
                {
                  "properties": {
                    "data": {
                      "items": {
                        "$ref": "#/definitions/AwardLineItem"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                },
                {
                  "$ref": "#/definitions/Pagination"
                }
              ],
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "tags": [
          "award_line_items"
        ],
        "description": "Returns a list of line items for a specific award.",
        "operationId": "List Award Line Items",
        "summary": "List Award Line Items",
        "x-codeSamples": [
          {
            "label": "Curl",
            "source": "curl -H \"X-Api-Key: ${COMPANY_KEY}\" \\\n     -H \"X-User-Token: ${USER_TOKEN}\" \\\n     -H \"X-User-Email: ${USER_EMAIL}\" \\\n     -H \"Content-Type: application/vnd.api+json\" \\\n     \"https://api.us.workdayspend.com/services/awards/v1/awards/1/award_line_items\"\n"
          }
        ]
      }
    }
  },
  "definitions": {
    "Award": {
      "allOf": [
        {
          "$ref": "#/definitions/AwardBase"
        },
        {
          "properties": {
            "attributes": {
              "$ref": "#/definitions/AwardAttributes"
            },
            "links": {
              "$ref": "#/definitions/ResourceLinks"
            },
            "relationships": {
              "$ref": "#/definitions/AwardRelationship"
            }
          },
          "type": "object"
        }
      ]
    },
    "AwardAttributes": {
      "description": "Award attributes.",
      "properties": {
        "cons": {
          "$ref": "#/definitions/AwardCons"
        },
        "external_id": {
          "$ref": "#/definitions/AwardExternalId"
        },
        "pros": {
          "$ref": "#/definitions/AwardPros"
        },
        "state": {
          "$ref": "#/definitions/AwardState"
        },
        "title": {
          "$ref": "#/definitions/AwardTitle"
        },
        "updated_at": {
          "$ref": "#/definitions/AwardUpdatedAt"
        }
      },
      "required": [
        "title"
      ],
      "type": "object"
    },
    "AwardBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/AwardId"
        },
        "type": {
          "$ref": "#/definitions/AwardType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Award",
      "type": "object"
    },
    "AwardCons": {
      "description": "Cons associated with award option",
      "example": "<p>Expensive company</p>",
      "type": "string"
    },
    "AwardExternalId": {
      "description": "Award ID in your internal database.",
      "maxLength": 255,
      "type": "string"
    },
    "AwardId": {
      "description": "Award identifier string.",
      "example": 1,
      "type": "integer"
    },
    "AwardInputFilter": {
      "properties": {
        "state_equals": {
          "description": "Find awards by their state.",
          "example": [
            "draft",
            "confirmed"
          ],
          "type": "array"
        },
        "updated_at_from": {
          "description": "Return awards updated on or after the specified timestamp.",
          "example": "2021-05-29T21:28:46.790Z",
          "format": "date-time",
          "type": "string"
        },
        "updated_at_to": {
          "description": "Return awards updated on or before the specified timestamp.",
          "example": "2021-05-29T21:28:46.790Z",
          "format": "date-time",
          "type": "string"
        }
      },
      "type": "object"
    },
    "AwardLineItem": {
      "allOf": [
        {
          "$ref": "#/definitions/AwardLineItemBase"
        },
        {
          "properties": {
            "attributes": {
              "$ref": "#/definitions/AwardLineItemAttributes"
            },
            "relationships": {
              "$ref": "#/definitions/AwardLineItemRelationship"
            }
          },
          "type": "object"
        }
      ]
    },
    "AwardLineItemAttributes": {
      "description": "Award line item attributes.",
      "properties": {
        "allocated_quantity": {
          "description": "Award line item allocated quantity.",
          "type": "integer"
        },
        "data": {
          "additionalProperties": {
            "description": "Worksheet line item cell value.",
            "x-additionalPropertiesName": "value"
          },
          "description": "A hashmap where keys are data identifier strings for the columns in the worksheet,\nand values are cell values.\n",
          "properties": {
            "data_identifier": {
              "description": "Worksheet column identifier string.",
              "type": "string"
            }
          },
          "type": "object"
        },
        "is_quoted": {
          "description": "Identifies whether the award line item is quoted.",
          "type": "boolean"
        },
        "line_item_type": {
          "$ref": "#/definitions/AwardLineItemTypeEnum"
        },
        "net_savings": {
          "description": "Award line item net savings.",
          "type": "number"
        },
        "net_savings_percentage": {
          "description": "Award line item net savings percentage.",
          "type": "number"
        },
        "price": {
          "description": "Award line item unit price.",
          "type": "number"
        },
        "sought_quantity": {
          "description": "Award line item sought quantity.",
          "type": "integer"
        },
        "total_spend": {
          "description": "Award line item total spend.",
          "type": "number"
        }
      },
      "type": "object"
    },
    "AwardLineItemBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/AwardLineItemId"
        },
        "type": {
          "$ref": "#/definitions/AwardLineItemType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Award line item",
      "type": "object"
    },
    "AwardLineItemId": {
      "description": "Award line items identifier string.",
      "example": 1,
      "type": "integer"
    },
    "AwardLineItemInputFilter": {
      "properties": {
        "is_quoted_equals": {
          "description": "Return awards line items by their quoted state.",
          "example": true,
          "type": "boolean"
        },
        "line_item_type_equals": {
          "description": "Return awards line items with specified line item types.",
          "example": [
            "GOODS",
            "SERVICES"
          ],
          "items": {
            "$ref": "#/definitions/AwardLineItemTypeEnum"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "AwardLineItemRelatedResources": {
      "enum": [
        "supplier_company",
        "worksheet"
      ],
      "type": "string"
    },
    "AwardLineItemRelationship": {
      "description": "Award line item relationships.",
      "properties": {
        "supplier_company": {
          "properties": {
            "data": {
              "$ref": "#/definitions/SupplierCompanyBase"
            }
          },
          "type": "object"
        },
        "worksheet": {
          "properties": {
            "data": {
              "$ref": "#/definitions/WorksheetBase"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "AwardLineItemType": {
      "description": "Object type, should always be `award_line_items`.",
      "example": "award_line_items",
      "type": "string"
    },
    "AwardLineItemTypeEnum": {
      "description": "Award line item type.",
      "enum": [
        "STANDARD",
        "GOODS",
        "SERVICES"
      ],
      "example": "STANDARD",
      "type": "string"
    },
    "AwardPros": {
      "description": "Pros associated with award option",
      "example": "<p>Reliable company</p>",
      "type": "string"
    },
    "AwardRelationship": {
      "description": "Award relationships.",
      "properties": {
        "creator": {
          "description": "Project creator is the user whose API keys are used for authentication.",
          "properties": {
            "data": {
              "$ref": "#/definitions/StakeholderBase"
            }
          },
          "type": "object"
        },
        "project": {
          "description": "Project associated with this award.",
          "properties": {
            "data": {
              "$ref": "#/definitions/ProjectBase"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "AwardState": {
      "description": "Award state. The default value is `draft` when the award is created.",
      "enum": [
        "draft",
        "confirmed",
        "awaiting_requisition_sync",
        "requisition_created"
      ],
      "type": "string"
    },
    "AwardTitle": {
      "description": "Award title.",
      "maxLength": 255,
      "type": "string"
    },
    "AwardType": {
      "description": "Object type, should always be `awards`.",
      "example": "awards",
      "type": "string"
    },
    "AwardUpdateAttributes": {
      "description": "Award update attributes.",
      "properties": {
        "external_id": {
          "$ref": "#/definitions/AwardExternalId"
        },
        "state": {
          "$ref": "#/definitions/AwardState"
        },
        "title": {
          "$ref": "#/definitions/AwardTitle"
        }
      },
      "type": "object"
    },
    "AwardUpdatedAt": {
      "description": "Last modification date.",
      "example": "2021-05-29T21:28:46.790Z",
      "format": "date-time",
      "readOnly": true,
      "type": "string"
    },
    "Error": {
      "properties": {
        "detail": {
          "description": "A human-readable explanation specific to this occurrence of the problem.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Errors": {
      "properties": {
        "errors": {
          "items": {
            "$ref": "#/definitions/Error"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "NextPageLink": {
      "properties": {
        "next": {
          "description": "Link to the next results page.",
          "format": "url",
          "type": "string",
          "x-nullable": true
        }
      },
      "type": "object"
    },
    "PageInput": {
      "properties": {
        "size": {
          "description": "The number of results returned per page. Default is `10` and max is `100`.",
          "example": "25",
          "format": "integer",
          "type": "number"
        }
      },
      "type": "object"
    },
    "Pagination": {
      "properties": {
        "links": {
          "$ref": "#/definitions/PaginationLinks"
        },
        "meta": {
          "description": "Result set metadata.",
          "properties": {
            "count": {
              "description": "Number of pages in the result set.",
              "type": "integer"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "PaginationLinks": {
      "allOf": [
        {
          "$ref": "#/definitions/SelfLink"
        },
        {
          "$ref": "#/definitions/NextPageLink"
        },
        {
          "$ref": "#/definitions/PrevPageLink"
        }
      ],
      "description": "List of related links.",
      "type": "object"
    },
    "PaymentCurrency": {
      "allOf": [
        {
          "$ref": "#/definitions/PaymentCurrencyBase"
        }
      ]
    },
    "PaymentCurrencyBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/PaymentCurrencyId"
        },
        "type": {
          "$ref": "#/definitions/PaymentCurrencyType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Field",
      "type": "object"
    },
    "PaymentCurrencyId": {
      "description": "Payment currency identifier string.",
      "example": 1,
      "type": "integer"
    },
    "PaymentCurrencyType": {
      "description": "Object type, should always be `payment_currencies`.",
      "example": "payment_currencies",
      "type": "string"
    },
    "PrevPageLink": {
      "properties": {
        "prev": {
          "description": "Link to the previous results page.",
          "format": "url",
          "type": "string",
          "x-deprecated": true,
          "x-nullable": true
        }
      },
      "type": "object"
    },
    "Project": {
      "allOf": [
        {
          "$ref": "#/definitions/ProjectBase"
        }
      ]
    },
    "ProjectBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/ProjectId"
        },
        "type": {
          "$ref": "#/definitions/ProjectType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Project",
      "type": "object"
    },
    "ProjectId": {
      "description": "Project identifier string.",
      "example": 1,
      "type": "integer"
    },
    "ProjectType": {
      "description": "Object type, should always be `projects`.",
      "example": "projects",
      "type": "string"
    },
    "ResourceLinks": {
      "allOf": [
        {
          "$ref": "#/definitions/SelfLink"
        }
      ],
      "description": "List of related links.",
      "type": "object"
    },
    "SelfLink": {
      "properties": {
        "self": {
          "description": "Normalized link to the resource.",
          "format": "url",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StakeholderBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/StakeholderId"
        },
        "type": {
          "$ref": "#/definitions/StakeholderType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Stakeholder",
      "type": "object"
    },
    "StakeholderBaseData": {
      "properties": {
        "data": {
          "$ref": "#/definitions/StakeholderBase"
        }
      },
      "required": [
        "data"
      ],
      "title": "Stakeholder Data",
      "type": "object"
    },
    "StakeholderId": {
      "description": "Stakeholder identifier string.",
      "example": 1,
      "type": "integer"
    },
    "StakeholderType": {
      "description": "Object type, should always be `stakeholders`.",
      "example": "stakeholders",
      "type": "string"
    },
    "SupplierCompany": {
      "allOf": [
        {
          "$ref": "#/definitions/SupplierCompanyBase"
        }
      ]
    },
    "SupplierCompanyBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/SupplierCompanyId"
        },
        "type": {
          "$ref": "#/definitions/SupplierCompanyType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "SupplierCompany",
      "type": "object"
    },
    "SupplierCompanyId": {
      "description": "Supplier company identifier string.",
      "example": 1,
      "type": "integer"
    },
    "SupplierCompanyType": {
      "description": "Object type, should always be `supplier_companies`.",
      "example": "supplier_companies",
      "type": "string"
    },
    "WorksheetBase": {
      "properties": {
        "id": {
          "$ref": "#/definitions/WorksheetId"
        },
        "type": {
          "$ref": "#/definitions/WorksheetType"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "title": "Worksheet",
      "type": "object"
    },
    "WorksheetId": {
      "description": "Worksheet identifier string.",
      "example": 1,
      "type": "integer"
    },
    "WorksheetModel": {
      "allOf": [
        {
          "$ref": "#/definitions/WorksheetBase"
        }
      ]
    },
    "WorksheetType": {
      "description": "Object type, should always be `worksheets`.",
      "example": "worksheets",
      "type": "string"
    }
  },
  "securityDefinitions": {
    "api_key": {
      "description": "Company API key.",
      "in": "header",
      "name": "X-Api-Key",
      "type": "apiKey"
    },
    "user_email": {
      "description": "User email.",
      "in": "header",
      "name": "X-User-Email",
      "type": "apiKey"
    },
    "user_token": {
      "description": "User token.",
      "in": "header",
      "name": "X-User-Token",
      "type": "apiKey"
    }
  },
  "security": [
    {
      "api_key": []
    }
  ],
  "tags": [
    {
      "description": "Workday Strategic Sourcing API Support: Please have a Named Support Contact from your company submit a support case in Workday's Customer Center.\n",
      "name": "support",
      "x-displayName": "Customer Support"
    },
    {
      "description": "### US Region\n| Environment       | US region Base URI                                         |\n|-------------------|------------------------------------------------------------|\n| **Production**    | https://api.us.workdayspend.com/services/awards/v1         |\n| **Sandbox**       | https://api.sandbox.us.workdayspend.com/services/awards/v1 |\n\n### EU Region\n| Environment       | EU region Base URI                                                |\n|-------------------|-------------------------------------------------------------------|\n| **Production**    | https://api.eu.workdayspend.com/services/awards/v1          |\n| **Sandbox**       | https://api.sandbox.eu.workdayspend.com/services/awards/v1  |\n\n### CA Region\n| Environment       | CA region Base URI                                                |\n|-------------------|-------------------------------------------------------------------|\n| **Production**    | https://api.ca.workdayspend.com/services/awards/v1          |\n| **Sandbox**       | https://api.sandbox.ca.workdayspend.com/services/awards/v1  |\n",
      "name": "servers",
      "x-displayName": "Servers"
    },
    {
      "description": "The API conforms to the [JSON API Specification](https://jsonapi.org).\n\nThe current version of this service is indicated by the `X-Api-Version` header.\n\nSample version header: `X-Api-Version: 1.0`.\n",
      "name": "api_specification",
      "x-displayName": "API Specification"
    },
    {
      "description": "Our API adheres to the ISO 8601 standard when accepting and formatting Date and Time fields. All Date and Time fields returned by this API will be in the **UTC** timezone.\n\nDate and Time fields sent to this API can be in any timezone, provided they adhere to the ISO 8601 standard.\n",
      "name": "date_and_time_fields",
      "x-displayName": "Date and Time Fields"
    },
    {
      "description": "The Workday Strategic Sourcing API uses API keys to authenticate requests. Every request\nwill require all 3 HTTP headers:\n\n| HTTP Header       | Description               |\n|-------------------|---------------------------|\n| **X-Api-Key**     | a company-wide API key    |\n| **X-User-Token**  | a user-specific API token |\n| **X-User-Email**  | user email                |\n\nYou can generate all of those from the _API tokens_ section of your _Profile_ page.\n\nYour API keys carry many privileges, so be sure to keep them secure! Do not share your secret API\nkeys in publicly accessible areas such as GitHub, client-side code, and so forth.\n\nAll API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made\nover plain HTTP will fail. API requests without authentication will also fail.\n",
      "name": "authentication",
      "x-displayName": "Authentication"
    },
    {
      "description": "Rate limit windows are per second and are shared by all API Keys for a company.\n\nThe rate limit is 5 requests per second.\n\nWhen request submissions exceed the limits, the limit-exceeding requests return `429 Too Many Requests` error responses to the client.\n\nUpon receiving a `429` response, it is recommended to retry the request in compliance with the rate limit. One example would be to add a sleep function for 1 second and retry.\n",
      "name": "rate_limiting",
      "x-displayName": "Rate Limiting"
    },
    {
      "description": "The results can be filtered to a subset of the total set of results using `filter` query parameters.\n\nEndpoints that support filtering will include usage details in the Query Parameters section for the resource.\n\nMost filters that end in `equals` support a Query Parameter array format to filter by multiple values.\n\nExample:\n```\n?filter[status_equals][]=submitted&filter[status_equals][]=resubmitted\n```\n",
      "name": "filters",
      "x-displayName": "Filters"
    },
    {
      "description": "Paginated endpoints may return a subset of the total results for a `GET` request that returns multiple resources. Endpoints that support pagination will include usage details in the Query Parameters section for the resource.\n\nThe paginated results can be configured using the `page` query parameter to configure the number of returned results. The default pagination size is 10 results and the maximum pagination size is 100 results per request.\n\nEndpoints that support pagination may return \"self\" and \"next\" sections within the \"links\" section that navigate to the current and next pages respectively.\n\n\n### Example Paginated Request\n\n#### Request Query Parameter Format\n```\n/projects?page[size]=25\n```\n\n#### Response Schema\nThe paginated response will also include the following schema\n\n<SchemaDefinition schemaRef=\"#/components/schemas/Pagination\" exampleRef=\"#/components/examples/Pagination\" />\n",
      "name": "pagination",
      "x-displayName": "Pagination"
    },
    {
      "description": "The `external_id` field exists on many of the Workday Strategic Sourcing resources. This optional and mutable extension is intended to store foreign keys of the corresponding resource from a third party system. **These IDs are not considered Sourcing Data and may be logged in external systems. Do not include any sensitive or personal data in IDs.**\n\nThe purpose of external IDs is to:\n\n* Prevent duplicate record creation\n* Allow resources in Workday Strategic Sourcing and a third party system to share the same identifier\n* Allow for records to be queried or updated without requiring knowledge of the Workday Strategic Sourcing generated IDs\n",
      "name": "external_ids",
      "x-displayName": "External Identifiers (IDs)"
    },
    {
      "description": "Use the Awards API to query the Awards in Workday Strategic Sourcing.\n\nAwards are used for procurement.\n\n## Award Object\n\n<SchemaDefinition schemaRef=\"#/components/schemas/Award\" showReadOnly={true} showWriteOnly={true} />\n",
      "name": "awards",
      "x-displayName": "Awards"
    },
    {
      "description": "Use the Award Line Items API to query the Award Line Items in Workday Strategic Sourcing.\n\nAward Line Items are used for procurement.\n\n## Award Line Item Object\n\n<SchemaDefinition schemaRef=\"#/components/schemas/AwardLineItem\" exampleRef=\"#/components/examples/AwardLineItem\" showReadOnly={true} showWriteOnly={true} />\n",
      "name": "award_line_items",
      "x-displayName": "Award Line Items"
    }
  ],
  "x-components": {
    "examples": {
      "AwardLineItem": {
        "$ref": "#/x-components/examples/award_line_item"
      },
      "Pagination": {
        "$ref": "#/x-components/examples/pagination"
      },
      "award_line_item": {
        "value": {
          "attributes": {
            "allocated_quantity": 1,
            "data": {
              "c263": "Worksheet 1 line item 1",
              "c264": 1,
              "c265": 10,
              "c266": 10,
              "c268": 0
            },
            "is_quoted": true,
            "line_item_type": "STANDARD",
            "net_savings": -10,
            "net_savings_percentage": null,
            "price": 10,
            "sought_quantity": 1,
            "total_spend": 10
          },
          "id": "1_5",
          "relationships": {
            "supplier_company": {
              "data": {
                "id": "1",
                "type": "supplier_companies"
              }
            },
            "worksheet": {
              "data": {
                "id": "2",
                "type": "worksheets"
              }
            }
          },
          "type": "award_line_items"
        }
      },
      "index_response": {
        "value": {
          "data": [
            {
              "attributes": {
                "cons": "<p>Expensive</p>",
                "external_id": null,
                "pros": "<p>Reliable</p>",
                "state": "draft",
                "title": "Award #1 title",
                "updated_at": "2021-05-29T21:28:46.790Z"
              },
              "id": "1",
              "relationships": {
                "creator": {
                  "data": {
                    "id": "1",
                    "type": "stakeholders"
                  }
                },
                "project": {
                  "data": {
                    "id": "1",
                    "type": "projects"
                  }
                }
              },
              "type": "awards"
            },
            {
              "attributes": {
                "cons": null,
                "external_id": "AW-2",
                "pros": null,
                "state": "draft",
                "title": "Award #2 title",
                "updated_at": "2021-05-29T21:28:46.790Z"
              },
              "id": "2",
              "relationships": {
                "creator": {
                  "data": {
                    "id": "2",
                    "type": "stakeholders"
                  }
                },
                "project": {
                  "data": {
                    "id": "2",
                    "type": "projects"
                  }
                }
              },
              "type": "awards"
            }
          ],
          "links": {
            "next": "https://api.us.workdayspend.com/services/awards/v1/awards?page%5Bcursor%5D=WzgzXQ%3D%3D&page%5Bdirection%5D=next&page%5Bsize%5D=10",
            "prev": null,
            "self": "https://api.us.workdayspend.com/services/awards/v1/awards?page%5Bsize%5D=10"
          },
          "meta": {
            "count": 2
          }
        }
      },
      "index_response-2": {
        "value": {
          "data": [
            {
              "attributes": {
                "allocated_quantity": 1,
                "data": {
                  "c263": "Worksheet 1 line item 1",
                  "c264": 1,
                  "c265": 10,
                  "c266": 10,
                  "c268": 0
                },
                "is_quoted": true,
                "line_item_type": "STANDARD",
                "net_savings": -10,
                "net_savings_percentage": null,
                "price": 10,
                "sought_quantity": 1,
                "total_spend": 10
              },
              "id": "1_5",
              "relationships": {
                "supplier_company": {
                  "data": {
                    "id": "1",
                    "type": "supplier_companies"
                  }
                },
                "worksheet": {
                  "data": {
                    "id": "2",
                    "type": "worksheets"
                  }
                }
              },
              "type": "award_line_items"
            },
            {
              "attributes": {
                "allocated_quantity": 2,
                "data": {
                  "c263": "Worksheet 1 line item 2",
                  "c264": 2,
                  "c265": 20,
                  "c266": 40,
                  "c267": 30,
                  "c268": 60
                },
                "is_quoted": true,
                "line_item_type": "STANDARD",
                "net_savings": 20,
                "net_savings_percentage": 33.33,
                "price": 20,
                "sought_quantity": 2,
                "total_spend": 40
              },
              "id": "1_6",
              "relationships": {
                "supplier_company": {
                  "data": {
                    "id": "1",
                    "type": "supplier_companies"
                  }
                },
                "worksheet": {
                  "data": {
                    "id": "2",
                    "type": "worksheets"
                  }
                }
              },
              "type": "award_line_items"
            }
          ],
          "links": {
            "next": "https://api.us.workdayspend.com/services/awards/v1/awards/1/award_line_items?page%5Bcursor%5D=WzE0MV0&page%5Bdirection%5D=next&page%5Bsize%5D=10",
            "prev": null,
            "self": "https://api.us.workdayspend.com/services/awards/v1/awards/1/award_line_items?page%5Bsize%5D=10"
          },
          "meta": {
            "count": 2
          }
        }
      },
      "pagination": {
        "value": {
          "data": {
            "key": "value"
          },
          "links": {
            "next": "https://api.us.workdayspend.com/services/awards/v1/projects?page[cursor]=WzFd&page[direction]=next&page[size]=25",
            "prev": null,
            "self": "https://api.us.workdayspend.com/services/awards/v1/projects"
          },
          "meta": {
            "count": 2
          }
        }
      },
      "show_response": {
        "value": {
          "data": {
            "attributes": {
              "allocated_quantity": 1,
              "data": {
                "c263": "Worksheet 1 line item 1",
                "c264": 1,
                "c265": 10,
                "c266": 10,
                "c268": 0
              },
              "is_quoted": true,
              "line_item_type": "STANDARD",
              "net_savings": -10,
              "net_savings_percentage": null,
              "price": 10,
              "sought_quantity": 1,
              "total_spend": 10
            },
            "id": "1_5",
            "relationships": {
              "supplier_company": {
                "data": {
                  "id": "1",
                  "type": "supplier_companies"
                }
              },
              "worksheet": {
                "data": {
                  "id": "2",
                  "type": "worksheets"
                }
              }
            },
            "type": "award_line_items"
          }
        }
      },
      "update_request": {
        "value": {
          "data": {
            "attributes": {
              "external_id": "AW-1",
              "state": "confirmed",
              "title": "Award #1 title"
            },
            "id": "1",
            "type": "awards"
          }
        }
      },
      "update_response": {
        "value": {
          "data": {
            "attributes": {
              "cons": null,
              "external_id": "AW-1",
              "pros": null,
              "state": "confirmed",
              "title": "Award #1 title"
            },
            "id": "1",
            "relationships": {
              "creator": {
                "data": {
                  "id": "1",
                  "type": "stakeholders"
                }
              },
              "project": {
                "data": {
                  "id": "1",
                  "type": "projects"
                }
              }
            },
            "type": "awards"
          }
        }
      }
    }
  },
  "x-tagGroups": [
    {
      "tags": [
        "support",
        "servers",
        "api_specification",
        "date_and_time_fields",
        "authentication",
        "rate_limiting",
        "external_ids",
        "pagination",
        "filters"
      ],
      "name": "Getting Started"
    },
    {
      "tags": [
        "awards",
        "award_line_items"
      ],
      "name": "Awards"
    }
  ]
}
